// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvddoaxhaavvgrulnska.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2ZGRvYXhoYWF2dmdydWxuc2thIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MzAxNzcsImV4cCI6MjA3MTIwNjE3N30.j1-srpsOPWUFzmGvfor6gglpRO_X2Z2PJhM4bEsdbE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});